identifier: "default"

logging.level.root: error

sampleEntryA:
  name: "John Doe"
  number: "0123456789"
  
sampleEntryB:
   name: "Jane Doe"
   number: "9876543210"
   
sampleEntryCommon:
   name: "Common cust"
   number: "1111111111"
